{{ if .Values.chainspec.createConfigmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "polkadot-deployer.custom-chainspec-configmap" . }}
data:
  custom_chainspec.json: |-
    {{- $totalItems := len .Values.chainspec.keys.stash }}
    {{- $lastIndex := sub $totalItems 1 }}
    {
      "name": {{ .Values.name | quote }},
      "id": {{ .Values.name | quote }},
      "genesis": {
        "runtime": {
          "consensus": {
            "authorities": [
              {{- range $index, $value := .Values.chainspec.keys.session }}
              {{ $value | quote }}{{- if ne $index $lastIndex }},{{- end }}
              {{- end }}
            ]
          },
          "indices": {
            "ids": [
              {{- range $index, $value := .Values.chainspec.keys.stash }}
              {{ $value | quote }}{{- if ne $index $lastIndex }},{{- end }}
              {{- end }}
            ]
          },
          "balances": {
            "balances": [
              {{- range $index, $value := .Values.chainspec.keys.stash }}
              [
                {{ $value | quote }},
                1048576
              ]{{- if ne $index $lastIndex }},{{- end }}
              {{- end }}
            ]
          },
          "session": {
            "validators": [
              {{- range $index, $value := .Values.chainspec.keys.controller }}
              {{ $value | quote }}{{- if ne $index $lastIndex }},{{- end }}
              {{- end }}
            ],
            "keys": [
              {{- $sessionKeys := .Values.chainspec.keys.session }}
              {{- range $index, $value := .Values.chainspec.keys.controller }}
              [
                {{ $value | quote }},
                {{ index $sessionKeys $index | quote }}
              ]{{- if ne $index $lastIndex }},{{- end }}
              {{- end }}
            ]
          },
          "staking": {
            "validatorCount": {{ $totalItems }},
            "invulnerables": [
              {{- range $index, $value := .Values.chainspec.keys.controller }}
              {{ $value | quote }}{{- if ne $index $lastIndex }},{{- end }}
              {{- end }}
            ],
            "stakers": [
              {{- $controllers := .Values.chainspec.keys.controller }}
              {{- range $index, $value := .Values.chainspec.keys.stash }}
              [
                {{ $value | quote }},
                {{ index $controllers $index | quote }},
                5000,
                "Validator"
              ]{{- if ne $index $lastIndex }},{{- end }}
              {{- end }}
            ]
          },
          "grandpa": {
            "authorities": [
              {{- range $index, $value := .Values.chainspec.keys.session }}
              [
                {{ $value | quote }},
                1
              ]{{- if ne $index $lastIndex }},{{- end }}
              {{- end }}
            ]
          },
          "councilSeats": {
            "activeCouncil": [
              {{- range $index, $value := .Values.chainspec.keys.stash }}
              [
                {{ $value | quote }},
                1000000
              ]{{- if ne $index $lastIndex }},{{- end }}
              {{- end }}
            ]
          },
          "sudo": {
            "key": " {{ index .Values.chainspec.keys.controller 0 }}"
          }
        }
      }
    }
{{ end }}
