image:
  repo: parity/substrate
  tag: 2.0.0-f05cd69a0

initImage:
  repo: web3f/polkadot-deployer
  tag: latest

chainspec:
  custom: true
  createConfigmap: false
  path: "/chainspec/chainspec.json"

mainNode: false

mainNodeID: QmRpheLN4JWdAnY7HGJfWFNbfkQCb6tFf4vvA6hgjMZKrR
nodeKey: "0000000000000000000000000000000000000000000000000000000000000001"

validator: true

resources: {}
#  requests:
#    memory: "5Gi"
#    cpu: "1.5"

persistence:
  enabled: false
  dataSize: 32Gi
  chainspecSize: 10Mi
  storageClassName: standard
  accessModes: [ "ReadWriteOnce" ]
